#pragma once

namespace turbolang {
    enum DataType {
        DATA_TYPE_VOID = 0,
        DATA_TYPE_BOOL = 1, DATA_TYPE_BOOL_PTR = 2,
        DATA_TYPE_BYTE = 3, DATA_TYPE_UBYTE = 4, DATA_TYPE_BYTE_PTR = 5, DATA_TYPE_UBYTE_PTR = 6,
        DATA_TYPE_SHORT = 7, DATA_TYPE_USHORT = 8, DATA_TYPE_SHORT_PTR = 9, DATA_TYPE_USHORT_PTR = 10,
        DATA_TYPE_INT = 11,  DATA_TYPE_UINT = 12, DATA_TYPE_INT_PTR = 13, DATA_TYPE_UINT_PTR = 14,
        DATA_TYPE_LONG = 15, DATA_TYPE_ULONG = 16, DATA_TYPE_LONG_PTR = 17, DATA_TYPE_ULONG_PTR = 18,
        DATA_TYPE_FLOAT = 19, DATA_TYPE_FLOAT_PTR = 20,
        DATA_TYPE_DOUBLE = 21, DATA_TYPE_DOUBLE_PTR = 22
    };
}